name: Deploy Pacman Game (robusto)

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Gerar Pacman Graph
        run: |
          mkdir -p dist
          cd pacman-generator
          node --input-type=module -e "
            import pkg from './dist/pacman-contribution-graph.min.js';
            import fs from 'fs';
            const light = pkg.generate('Rafael072187', { theme: 'light' });
            const dark = pkg.generate('Rafael072187', { theme: 'dark' });
            fs.mkdirSync('../dist', { recursive: true });
            fs.writeFileSync('../dist/pacman-contribution-graph.svg', light);
            fs.writeFileSync('../dist/pacman-contribution-graph-dark.svg', dark);
          "
          cd ..


      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
