name: Deploy Pacman Game

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure dist folder and copy Pacman SVGs
        run: |
          mkdir -p dist
          # Se os arquivos estiverem na raiz, mantenha assim:
          cp pacman-contribution-graph.svg dist/
          cp pacman-contribution-graph-dark.svg dist/
          # Caso estejam em uma pasta, ajuste o caminho, ex:
          # cp assets/pacman-contribution-graph.svg dist/
          # cp assets/pacman-contribution-graph-dark.svg dist/

      - name: Deploy Pacman Game
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
