name: Deploy Pacman Game (robusto)

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Clonar gerador Pacman
        run: |
          git clone https://github.com/abozanona/pacman-contribution-graph pacman-generator
          cd pacman-generator
          npm install
          npm run build
          node dist/index.js --user Rafael072187 --output ../dist

      - name: Verificar geração dos arquivos
        run: |
          echo "Conteúdo da pasta dist:"
          ls -l dist

      - name: Publicar SVGs na branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
