name: Deploy Pacman Game (robusto)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Show current branch and files (debug)
        run: |
          echo "Branch: $GITHUB_REF"
          git --version
          ls -la

      - name: Ensure dist folder and copy Pacman SVGs (ajuste caminhos se necessário)
        run: |
          set -e
          mkdir -p dist
          # Ajuste os paths abaixo caso seus SVGs estejam em pasta diferente.
          if [ -f "pacman-contribution-graph.svg" ]; then
            cp pacman-contribution-graph.svg dist/
          else
            echo "Arquivo pacman-contribution-graph.svg não encontrado na raiz. Abortando."
            ls -la
            exit 1
          fi
          if [ -f "pacman-contribution-graph-dark.svg" ]; then
            cp pacman-contribution-graph-dark.svg dist/
          else
            echo "Arquivo pacman-contribution-graph-dark.svg não encontrado na raiz. Abortando."
            ls -la
            exit 1
          fi
          echo "Arquivos copiados para dist/:"
          ls -la dist

      - name: Prepare output branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin
          # cria (ou reseta) branch output localmente
          git checkout -B output

      - name: Move dist content to repo root (for gh-pages action)
        run: |
          # limpa pasta raiz temporariamente e copia dist content
          rm -rf output_tmp || true
          mkdir -p output_tmp
          cp -r dist/* output_tmp/
          ls -la output_tmp

      - name: Commit changes (if any)
        run: |
          cd output_tmp
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b output || true
          git add -A
          git commit -m "Atualiza Pacman output [ci]" || echo "Sem mudanças para commitar"
          git push origin output --force-with-lease

      - name: Done
        run: echo "Deploy concluído."

