name: Deploy Pacman Game (robusto)

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Clonar repositório do gerador Pacman
        run: git clone https://github.com/abozanona/pacman-contribution-graph pacman-generator

      - name: Gerar Pacman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Rafael072187

      - name: Corrigir diretório dist (se necessário)
        run: |
          mkdir -p dist
          if [ -f pacman-generator/pacman-contribution-graph.svg ]; then
            mv pacman-generator/pacman-contribution-graph.svg dist/ || true
          fi
          if [ -f pacman-generator/pacman-contribution-graph-dark.svg ]; then
            mv pacman-generator/pacman-contribution-graph-dark.svg dist/ || true
          fi
          if [ -f pacman-contribution-graph.svg ]; then
            mv pacman-contribution-graph.svg dist/ || true
          fi
          if [ -f pacman-contribution-graph-dark.svg ]; then
            mv pacman-contribution-graph-dark.svg dist/ || true
          fi
          echo "Arquivos prontos para deploy:"
          ls -l dist || echo "⚠️ Nenhum SVG encontrado — verifique se a Action gerou corretamente."

      - name: Publicar SVGs na branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
