name: Deploy Pacman Game

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy existing Pacman files
        run: |
          mkdir -p dist
          cp pacman-contribution-graph.svg dist/
          cp pacman-contribution-graph-dark.svg dist/

      - name: Deploy Pacman Game
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
