name: Deploy Pacman Game (robusto)

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar dependências e gerar Pacman
        run: |
          git clone https://github.com/abozanona/pacman-contribution-graph pacman-generator
          cd pacman-generator
          npm install
          npm run build

          echo "🔧 Gerando SVGs do Pacman..."
          node --input-type=module -e "
            import { generate } from './dist/pacman-contribution-graph.min.js';
            import fs from 'fs';
            const light = generate('Rafael072187', { theme: 'light' });
            const dark = generate('Rafael072187', { theme: 'dark' });
            fs.mkdirSync('../dist', { recursive: true });
            fs.writeFileSync('../dist/pacman-contribution-graph.svg', light);
            fs.writeFileSync('../dist/pacman-contribution-graph-dark.svg', dark);
          "

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
