name: Deploy Pacman Game (robusto)

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clonar gerador Pacman
        run: |
          git clone https://github.com/abozanona/pacman-contribution-graph pacman-generator
          cd pacman-generator
          npm install
          npm run build || true
          cd ..

      - name: Gerar Pacman Graph
        run: |
          mkdir -p dist
          node pacman-generator/dist/pacman-contribution-graph.min.js Rafael072187 || echo "Gerando pacman manualmente..."
          cp pacman-generator/dist/pacman-contribution-graph.svg dist/
          cp pacman-generator/dist/pacman-contribution-graph-dark.svg dist/

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
